# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
# Mod properties
release_type=release
mod_version=2.1.2
maven_group=sptools
mod_id=sptools
archives_name=SupplementalTools
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.10
support_versions=1.21.10
# Dependencies
architectury_api_version=18.0.8
fabric_loader_version=0.18.4
fabric_api_version=0.138.4+1.21.10
yarn_mappings=1.21.10+build.3
neoforge_version=21.10.56-beta
neoforge_patch=1.21+build.4
# publish
modrinth_id=mMGSs9QN
curseforge_id=1011641
