s#\.incrementStat(#.awardStat(#g
s#\.getDefaultState()#.defaultBlockState()#g
s#\.getOffsetX()#.getStepX()#g
s#\.getOffsetY()#.getStepY()#g
s#\.getOffsetZ()#.getStepZ()#g
s#\.getPlacementState(#.getStateForPlacement(#g
s#\.getPlacementDirections()#.getNearestLookingDirections()#g
s#\.emitGameEvent(#.gameEvent(#g
s#\.addPersistentModifier(#.addPermanentModifier(#g
s#\.getWorld()#.getLevel()#g
s#\.getEntry(#.get(#g
s#\.sendEntityStatus(#.broadcastEntityEvent(#g
s#\.damage(#.hurtAndBreak(#g
s#context\.getBlockPos()#context.getClickedPos()#g
s#player\.getBlockPos()#player.blockPosition()#g
s#\.down()#.below()#g
s#\buseOnBlock\b#useOn#g
s#\bpostHit\b#hurtEnemy#g
s#\buseOnEntity\b#interactLivingEntity#g
