s#MapColor\.STONE_GRAY#MapColor.STONE#g
s#MapColor\.DEEPSLATE_GRAY#MapColor.DEEPSLATE#g
s#Stats\.USED\.getOrCreateStat(#Stats.ITEM_USED.get(#g
s#SoundEvents\.BLOCK_WOOD_PLACE#SoundEvents.WOOD_PLACE#g
s#\.getAbilities()\.creativeMode#.getAbilities().instabuild#g
s#\.isOf(#.is(#g
s#\.isIn(#.is(#g
s#\.getAttributeInstance(#.getAttribute(#g
s#\.useBlockPrefixedTranslationKey(#.useBlockDescriptionPrefix(#g
s#\.getEntityWorld(#.level(#g
s#UniformInt\.create(#UniformInt.of(#g
s#\.STATUS_EFFECT\b#.MOB_EFFECT#g
s#\.spawnEntity(#.addFreshEntity(#g
s#\.setOnFireFor(#.igniteForSeconds(#g
s#\.isTouchingWaterOrRain()#.isInWaterRainOrBubble()#g
s#\.isFireImmune()#.fireImmune()#g
s#\.isClient()#.isClientSide()#g
s#\.getVelocity()#.getDeltaMovement()#g
s#\.setVelocity(#.setDeltaMovement(#g
s#\.getTime()#.getGameTime()#g
s#\.getMainHandStack()#.getMainHandItem()#g
s#\.getStackInHand(#.getItemInHand(#g
s#\.getStack()#.getItemInHand()#g
s#DataProvider\.writeAllToPath(#DataProvider.saveAll(#g
s#CollisionContext\.absent()#CollisionContext.empty()#g
s#\.getReceivedRedstonePower(#.getBestNeighborSignal(#g
s#\.getSide()#.getClickedFace()#g
s#\.getHitPos()#.getClickLocation()#g
