# ===== Import full-path replacements (exact, order: specific before generic) =====
s#net\.minecraft\.advancement\.criterion\.Criteria#net.minecraft.advancements.triggers.CriteriaTriggers#g
s#net\.minecraft\.block\.enums\.NoteBlockInstrument#net.minecraft.world.level.block.state.properties.NoteBlockInstrument#g
s#net\.minecraft\.block\.piston\.PistonBehavior#net.minecraft.world.level.material.PushReaction#g
s#net\.minecraft\.block\.AbstractBlock#net.minecraft.world.level.block.state.BlockBehaviour#g
s#net\.minecraft\.block\.BlockState#net.minecraft.world.level.block.state.BlockState#g
s#net\.minecraft\.block\.ExperienceDroppingBlock#net.minecraft.world.level.block.DropExperienceBlock#g
s#net\.minecraft\.block\.ShapeContext#net.minecraft.world.phys.shapes.CollisionContext#g
s#net\.minecraft\.block\.Blocks#net.minecraft.world.level.block.Blocks#g
s#net\.minecraft\.block\.Block#net.minecraft.world.level.block.Block#g
s#net\.minecraft\.client\.MinecraftClient#net.minecraft.client.Minecraft#g
s#net\.minecraft\.client\.network\.ClientPlayNetworkHandler#net.minecraft.client.multiplayer.ClientPacketListener#g
s#net\.minecraft\.client\.render\.Camera#net.minecraft.client.Camera#g
s#net\.minecraft\.client\.render\.entity\.equipment\.EquipmentModel#net.minecraft.client.resources.model.EquipmentClientInfo#g
s#net\.minecraft\.client\.render\.fog\.FogRenderer#net.minecraft.client.renderer.fog.FogRenderer#g
s#net\.minecraft\.client\.world\.ClientWorld#net.minecraft.client.multiplayer.ClientLevel#g
s#net\.minecraft\.component\.DataComponentTypes#net.minecraft.core.component.DataComponents#g
s#net\.minecraft\.component\.type\.EquippableComponent#net.minecraft.world.item.equipment.Equippable#g
s#net\.minecraft\.component\.type\.FireworksComponent#net.minecraft.world.item.component.Fireworks#g
s#net\.minecraft\.component\.type\.TooltipDisplayComponent#net.minecraft.world.item.component.TooltipDisplay#g
s#net\.minecraft\.data\.DataOutput#net.minecraft.data.PackOutput#g
s#net\.minecraft\.data\.DataWriter#net.minecraft.data.CachedOutput#g
s#net\.minecraft\.entity\.attribute\.EntityAttributeInstance#net.minecraft.world.entity.ai.attributes.AttributeInstance#g
s#net\.minecraft\.entity\.attribute\.EntityAttributeModifier#net.minecraft.world.entity.ai.attributes.AttributeModifier#g
s#net\.minecraft\.entity\.attribute\.EntityAttributes#net.minecraft.world.entity.ai.attributes.Attributes#g
s#net\.minecraft\.entity\.damage\.DamageSource#net.minecraft.world.damagesource.DamageSource#g
s#net\.minecraft\.entity\.damage\.DamageTypes#net.minecraft.world.damagesource.DamageTypes#g
s#net\.minecraft\.entity\.effect\.StatusEffectInstance#net.minecraft.world.effect.MobEffectInstance#g
s#net\.minecraft\.entity\.effect\.StatusEffectCategory#net.minecraft.world.effect.MobEffectCategory#g
s#net\.minecraft\.entity\.effect\.StatusEffects#net.minecraft.world.effect.MobEffects#g
s#net\.minecraft\.entity\.effect\.StatusEffect#net.minecraft.world.effect.MobEffect#g
s#net\.minecraft\.entity\.player\.PlayerEntity#net.minecraft.world.entity.player.Player#g
s#net\.minecraft\.entity\.projectile\.FireworkRocketEntity#net.minecraft.world.entity.projectile.FireworkRocketEntity#g
s#net\.minecraft\.entity\.EquipmentSlot#net.minecraft.world.entity.EquipmentSlot#g
s#net\.minecraft\.entity\.LivingEntity#net.minecraft.world.entity.LivingEntity#g
s#net\.minecraft\.entity\.Entity#net.minecraft.world.entity.Entity#g
s#net\.minecraft\.item\.BlockItem#net.minecraft.world.item.BlockItem#g
s#net\.minecraft\.item\.ItemPlacementContext#net.minecraft.world.item.context.BlockPlaceContext#g
s#net\.minecraft\.item\.ItemUsageContext#net.minecraft.world.item.context.UseOnContext#g
s#net\.minecraft\.item\.ItemStack#net.minecraft.world.item.ItemStack#g
s#net\.minecraft\.item\.Items#net.minecraft.world.item.Items#g
s#net\.minecraft\.item\.SmithingTemplateItem#net.minecraft.world.item.SmithingTemplateItem#g
s#net\.minecraft\.item\.ToolMaterial#net.minecraft.world.item.ToolMaterial#g
s#net\.minecraft\.item\.equipment\.ArmorMaterial#net.minecraft.world.item.equipment.ArmorMaterial#g
s#net\.minecraft\.item\.equipment\.EquipmentAsset#net.minecraft.world.item.equipment.EquipmentAsset#g
s#net\.minecraft\.item\.equipment\.EquipmentType#net.minecraft.world.item.equipment.EquipmentType#g
s#net\.minecraft\.item\.tooltip\.TooltipType#net.minecraft.world.item.TooltipFlag#g
s#net\.minecraft\.item\.Item#net.minecraft.world.item.Item#g
s#net\.minecraft\.particle\.ParticleTypes#net.minecraft.core.particles.ParticleTypes#g
s#net\.minecraft\.registry\.Registries#net.minecraft.core.registries.BuiltInRegistries#g
s#net\.minecraft\.registry\.RegistryKeys#net.minecraft.core.registries.Registries#g
s#net\.minecraft\.registry\.RegistryKey#net.minecraft.resources.ResourceKey#g
s#net\.minecraft\.registry\.entry\.RegistryEntry#net.minecraft.core.Holder#g
s#net\.minecraft\.registry\.tag\.BlockTags#net.minecraft.tags.BlockTags#g
s#net\.minecraft\.registry\.tag\.DamageTypeTags#net.minecraft.tags.DamageTypeTags#g
s#net\.minecraft\.registry\.tag\.TagKey#net.minecraft.tags.TagKey#g
s#net\.minecraft\.registry\.Registry#net.minecraft.core.Registry#g
s#net\.minecraft\.server\.network\.ServerPlayerEntity#net.minecraft.server.level.ServerPlayer#g
s#net\.minecraft\.sound\.BlockSoundGroup#net.minecraft.world.level.block.SoundType#g
s#net\.minecraft\.sound\.SoundCategory#net.minecraft.sounds.SoundSource#g
s#net\.minecraft\.sound\.SoundEvents#net.minecraft.sounds.SoundEvents#g
s#net\.minecraft\.sound\.SoundEvent#net.minecraft.sounds.SoundEvent#g
s#net\.minecraft\.stat\.Stats#net.minecraft.stats.Stats#g
s#net\.minecraft\.text\.Text#net.minecraft.network.chat.Component#g
s#net\.minecraft\.util\.ActionResult#net.minecraft.world.InteractionResult#g
s#net\.minecraft\.util\.Formatting#net.minecraft.ChatFormatting#g
s#net\.minecraft\.util\.Hand#net.minecraft.world.InteractionHand#g
s#net\.minecraft\.util\.Identifier#net.minecraft.resources.ResourceLocation#g
s#net\.minecraft\.util\.Rarity#net.minecraft.world.item.Rarity#g
s#net\.minecraft\.util\.math\.BlockPos#net.minecraft.core.BlockPos#g
s#net\.minecraft\.util\.math\.Box#net.minecraft.world.phys.AABB#g
s#net\.minecraft\.util\.math\.ColorHelper#net.minecraft.util.ARGB#g
s#net\.minecraft\.util\.math\.Direction#net.minecraft.core.Direction#g
s#net\.minecraft\.util\.math\.Vec3d#net.minecraft.world.phys.Vec3#g
s#net\.minecraft\.util\.math\.intprovider\.UniformIntProvider#net.minecraft.util.valueproviders.UniformInt#g
s#net\.minecraft\.util\.math\.intprovider\.IntProvider#net.minecraft.util.valueproviders.IntProvider#g
s#net\.minecraft\.world\.event\.GameEvent#net.minecraft.world.level.gameevent.GameEvent#g
s#net\.minecraft\.world\.World#net.minecraft.world.level.Level#g
# ===== In-code simple-name replacements (ordered: specific before generic) =====
s#\bBlock\.Settings\b#BlockBehaviour.Properties#g
s#\bAbstractBlock\b#BlockBehaviour#g
s#\bExperienceDroppingBlock\b#DropExperienceBlock#g
s#\bShapeContext\b#CollisionContext#g
s#\bNoteBlockInstrument\b#NoteBlockInstrument#g
s#\bPistonBehavior\b#PushReaction#g
s#\bMinecraftClient\b#Minecraft#g
s#\bClientPlayNetworkHandler\b#ClientPacketListener#g
s#\bClientWorld\b#ClientLevel#g
s#\bEquipmentModel\b#EquipmentClientInfo#g
s#\bDataComponentTypes\b#DataComponents#g
s#\bEquippableComponent\b#Equippable#g
s#\bFireworksComponent\b#Fireworks#g
s#\bTooltipDisplayComponent\b#TooltipDisplay#g
s#\bDataOutput\b#PackOutput#g
s#\bDataWriter\b#CachedOutput#g
s#\bEntityAttributeInstance\b#AttributeInstance#g
s#\bEntityAttributeModifier\b#AttributeModifier#g
s#\bEntityAttributes\b#Attributes#g
s#\bStatusEffectInstance\b#MobEffectInstance#g
s#\bStatusEffectCategory\b#MobEffectCategory#g
s#\bStatusEffects\b#MobEffects#g
s#\bStatusEffect\b#MobEffect#g
s#\bServerPlayerEntity\b#ServerPlayer#g
s#\bPlayerEntity\b#Player#g
s#\bItemPlacementContext\b#BlockPlaceContext#g
s#\bItemUsageContext\b#UseOnContext#g
s#\bTooltipType\b#TooltipFlag#g
s#\bRegistries\b#BuiltInRegistries#g
s#\bRegistryKeys\b#Registries#g
s#\bRegistryKey\b#ResourceKey#g
s#\bRegistryEntry\b#Holder#g
s#\bBlockSoundGroup\b#SoundType#g
s#\bSoundCategory\b#SoundSource#g
s#\bColorHelper\b#ARGB#g
s#\bVec3d\b#Vec3#g
s#\bUniformIntProvider\b#UniformInt#g
s#\bCriteria\b#CriteriaTriggers#g
s#\bText\b#Component#g
s#\bActionResult\b#InteractionResult#g
s#\bFormatting\b#ChatFormatting#g
s#\bIdentifier\b#ResourceLocation#g
s#\bHand\b#InteractionHand#g
s#\bBox\b#AABB#g
s#\bItem\.Settings\b#Item.Properties#g
s#\bWorld\b#Level#g
s#BlockBehaviour\.Settings#BlockBehaviour.Properties#g
