package net.syshima.sptools.neoforge.datagen.providers;

import net.minecraft.block.Block;
import net.minecraft.data.DataOutput;
import net.minecraft.data.tag.TagProvider;
import net.minecraft.item.Item;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.ItemTags;
import net.neoforged.neoforge.common.data.BlockTagCopyingItemTagProvider;
import net.neoforged.neoforge.data.event.GatherDataEvent;
import net.syshima.sptools.Constants;
import net.syshima.sptools.ModItems;
import net.syshima.sptools.ModTags;
import org.jetbrains.annotations.NotNull;

import java.util.concurrent.CompletableFuture;

public class ModItemTagsProvider implements GatherDataEvent.ItemTagsProvider {
    @Override
    public @NotNull TagProvider<Item> create(@NotNull DataOutput dataOutput, @NotNull CompletableFuture<RegistryWrapper.WrapperLookup> lookupCompletableFuture, @NotNull CompletableFuture<TagProvider.TagLookup<Block>> tagLookupCompletableFuture) {
        return new ModItemTagProvider(dataOutput, lookupCompletableFuture, tagLookupCompletableFuture);
    }

    private static class ModItemTagProvider extends BlockTagCopyingItemTagProvider {

        public ModItemTagProvider(DataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture, CompletableFuture<TagProvider.TagLookup<Block>> tagLookupCompletableFuture) {
            super(output, registriesFuture, tagLookupCompletableFuture, Constants.MOD_ID);
        }

        @Override
        protected void configure(RegistryWrapper.WrapperLookup registries) {
            getTagBuilder(ModTags.Bronzes)
                    .add(ModItems.BRONZE_SWORD.getId())
                    .add(ModItems.BRONZE_PICKAXE.getId())
                    .add(ModItems.BRONZE_AXE.getId())
                    .add(ModItems.BRONZE_SHOVEL.getId())
                    .add(ModItems.BRONZE_HOE.getId())
                    .add(ModItems.BRONZE_HELMET.getId())
                    .add(ModItems.BRONZE_CHESTPLATE.getId())
                    .add(ModItems.BRONZE_LEGGINGS.getId())
                    .add(ModItems.BRONZE_BOOTS.getId());
            getTagBuilder(ModTags.IRONCOPPERS)
                    .add(ModItems.IRONCOPPER_SWORD.getId())
                    .add(ModItems.IRONCOPPER_PICKAXE.getId())
                    .add(ModItems.IRONCOPPER_AXE.getId())
                    .add(ModItems.IRONCOPPER_SHOVEL.getId())
                    .add(ModItems.IRONCOPPER_HOE.getId())
                    .add(ModItems.IRONCOPPER_HELMET.getId())
                    .add(ModItems.IRONCOPPER_CHESTPLATE.getId())
                    .add(ModItems.IRONCOPPER_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId());
            getTagBuilder(ModTags.AMETHYSTS)
                    .add(ModItems.AMETHYST_SWORD.getId())
                    .add(ModItems.AMETHYST_PICKAXE.getId())
                    .add(ModItems.AMETHYST_AXE.getId())
                    .add(ModItems.AMETHYST_SHOVEL.getId())
                    .add(ModItems.AMETHYST_HOE.getId())
                    .add(ModItems.AMETHYST_HELMET.getId())
                    .add(ModItems.AMETHYST_CHESTPLATE.getId())
                    .add(ModItems.AMETHYST_LEGGINGS.getId())
                    .add(ModItems.AMETHYST_BOOTS.getId());
            getTagBuilder(ModTags.EMERALDS)
                    .add(ModItems.EMERALD_SWORD.getId())
                    .add(ModItems.EMERALD_PICKAXE.getId())
                    .add(ModItems.EMERALD_AXE.getId())
                    .add(ModItems.EMERALD_SHOVEL.getId())
                    .add(ModItems.EMERALD_HOE.getId())
                    .add(ModItems.EMERALD_HELMET.getId())
                    .add(ModItems.EMERALD_CHESTPLATE.getId())
                    .add(ModItems.EMERALD_LEGGINGS.getId())
                    .add(ModItems.EMERALD_BOOTS.getId());
            getTagBuilder(ModTags.LEAD)
                    .add(ModItems.LEAD_SWORD.getId())
                    .add(ModItems.LEAD_PICKAXE.getId())
                    .add(ModItems.LEAD_AXE.getId())
                    .add(ModItems.LEAD_SHOVEL.getId())
                    .add(ModItems.LEAD_HOE.getId())
                    .add(ModItems.LEAD_HELMET.getId())
                    .add(ModItems.LEAD_CHESTPLATE.getId())
                    .add(ModItems.LEAD_LEGGINGS.getId())
                    .add(ModItems.LEAD_BOOTS.getId());
            getTagBuilder(ModTags.QUARTZ)
                    .add(ModItems.QUARTZ_SWORD.getId())
                    .add(ModItems.QUARTZ_PICKAXE.getId())
                    .add(ModItems.QUARTZ_AXE.getId())
                    .add(ModItems.QUARTZ_SHOVEL.getId())
                    .add(ModItems.QUARTZ_HOE.getId())
                    .add(ModItems.QUARTZ_HELMET.getId())
                    .add(ModItems.QUARTZ_CHESTPLATE.getId())
                    .add(ModItems.QUARTZ_LEGGINGS.getId())
                    .add(ModItems.QUARTZ_BOOTS.getId());
            getTagBuilder(ModTags.REDSTONE)
                    .add(ModItems.REDSTONE_SWORD.getId())
                    .add(ModItems.REDSTONE_PICKAXE.getId())
                    .add(ModItems.REDSTONE_AXE.getId())
                    .add(ModItems.REDSTONE_SHOVEL.getId())
                    .add(ModItems.REDSTONE_HOE.getId())
                    .add(ModItems.REDSTONE_HELMET.getId())
                    .add(ModItems.REDSTONE_CHESTPLATE.getId())
                    .add(ModItems.REDSTONE_LEGGINGS.getId())
                    .add(ModItems.REDSTONE_BOOTS.getId());
            getTagBuilder(ModTags.LAVA)
                    .add(ModItems.LAVA_HELMET.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());
            getTagBuilder(ModTags.DURABLE)
                    .add(ModItems.DURABLE_FIREWORK_ROCKET.getId())
                    .add(ModItems.DURABLE_FIREWORK_ROCKET_UPGRADED.getId())
                    .add(ModItems.DURABLE_TOTEM_OF_UNDYING.getId())
                    .add(ModItems.DURABLE_TOTEM_OF_UNDYING_UPGRADED.getId())
                    .add(ModItems.DURABLE_TORCH.getId())
                    .add(ModItems.DURABLE_TORCH_UPGRADED.getId());

            getTagBuilder(ItemTags.CLUSTER_MAX_HARVESTABLES)
                    .add(ModItems.BRONZE_PICKAXE.getId())
                    .add(ModItems.IRONCOPPER_PICKAXE.getId())
                    .add(ModItems.AMETHYST_PICKAXE.getId())
                    .add(ModItems.EMERALD_PICKAXE.getId())
                    .add(ModItems.LEAD_PICKAXE.getId())
                    .add(ModItems.QUARTZ_PICKAXE.getId())
                    .add(ModItems.REDSTONE_PICKAXE.getId());

            getTagBuilder(ItemTags.SWORDS)
                    .add(ModItems.BRONZE_SWORD.getId())
                    .add(ModItems.IRONCOPPER_SWORD.getId())
                    .add(ModItems.AMETHYST_SWORD.getId())
                    .add(ModItems.EMERALD_SWORD.getId())
                    .add(ModItems.LEAD_SWORD.getId())
                    .add(ModItems.QUARTZ_SWORD.getId())
                    .add(ModItems.REDSTONE_SWORD.getId());

            getTagBuilder(ItemTags.PICKAXES)
                    .add(ModItems.BRONZE_PICKAXE.getId())
                    .add(ModItems.IRONCOPPER_PICKAXE.getId())
                    .add(ModItems.AMETHYST_PICKAXE.getId())
                    .add(ModItems.EMERALD_PICKAXE.getId())
                    .add(ModItems.LEAD_PICKAXE.getId())
                    .add(ModItems.QUARTZ_PICKAXE.getId())
                    .add(ModItems.REDSTONE_PICKAXE.getId())
                    .add(ModItems.DURABLE_FIREWORK_ROCKET.getId())
                    .add(ModItems.DURABLE_FIREWORK_ROCKET_UPGRADED.getId())
                    .add(ModItems.DURABLE_TORCH.getId())
                    .add(ModItems.DURABLE_TORCH_UPGRADED.getId());

            getTagBuilder(ItemTags.AXES)
                    .add(ModItems.BRONZE_AXE.getId())
                    .add(ModItems.IRONCOPPER_AXE.getId())
                    .add(ModItems.AMETHYST_AXE.getId())
                    .add(ModItems.EMERALD_AXE.getId())
                    .add(ModItems.LEAD_AXE.getId())
                    .add(ModItems.QUARTZ_AXE.getId())
                    .add(ModItems.REDSTONE_AXE.getId());

            getTagBuilder(ItemTags.SHOVELS)
                    .add(ModItems.BRONZE_SHOVEL.getId())
                    .add(ModItems.IRONCOPPER_SHOVEL.getId())
                    .add(ModItems.AMETHYST_SHOVEL.getId())
                    .add(ModItems.EMERALD_SHOVEL.getId())
                    .add(ModItems.LEAD_SHOVEL.getId())
                    .add(ModItems.QUARTZ_SHOVEL.getId())
                    .add(ModItems.REDSTONE_SHOVEL.getId())
                    .add(ModItems.DURABLE_TOTEM_OF_UNDYING.getId())
                    .add(ModItems.DURABLE_TOTEM_OF_UNDYING_UPGRADED.getId());

            getTagBuilder(ItemTags.HOES)
                    .add(ModItems.BRONZE_HOE.getId())
                    .add(ModItems.IRONCOPPER_HOE.getId())
                    .add(ModItems.AMETHYST_HOE.getId())
                    .add(ModItems.EMERALD_HOE.getId())
                    .add(ModItems.LEAD_HOE.getId())
                    .add(ModItems.QUARTZ_HOE.getId())
                    .add(ModItems.REDSTONE_HOE.getId());

            getTagBuilder(ItemTags.HEAD_ARMOR)
                    .add(ModItems.BRONZE_HELMET.getId())
                    .add(ModItems.IRONCOPPER_HELMET.getId())
                    .add(ModItems.AMETHYST_HELMET.getId())
                    .add(ModItems.EMERALD_HELMET.getId())
                    .add(ModItems.LEAD_HELMET.getId())
                    .add(ModItems.QUARTZ_HELMET.getId())
                    .add(ModItems.REDSTONE_HELMET.getId())
                    .add(ModItems.LAVA_HELMET.getId());

            getTagBuilder(ItemTags.CHEST_ARMOR)
                    .add(ModItems.BRONZE_CHESTPLATE.getId())
                    .add(ModItems.IRONCOPPER_CHESTPLATE.getId())
                    .add(ModItems.AMETHYST_CHESTPLATE.getId())
                    .add(ModItems.EMERALD_CHESTPLATE.getId())
                    .add(ModItems.LEAD_CHESTPLATE.getId())
                    .add(ModItems.QUARTZ_CHESTPLATE.getId())
                    .add(ModItems.REDSTONE_CHESTPLATE.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId());

            getTagBuilder(ItemTags.LEG_ARMOR)
                    .add(ModItems.BRONZE_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_LEGGINGS.getId())
                    .add(ModItems.AMETHYST_LEGGINGS.getId())
                    .add(ModItems.EMERALD_LEGGINGS.getId())
                    .add(ModItems.LEAD_LEGGINGS.getId())
                    .add(ModItems.QUARTZ_LEGGINGS.getId())
                    .add(ModItems.REDSTONE_LEGGINGS.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId());

            getTagBuilder(ItemTags.FOOT_ARMOR)
                    .add(ModItems.BRONZE_BOOTS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId())
                    .add(ModItems.AMETHYST_BOOTS.getId())
                    .add(ModItems.EMERALD_BOOTS.getId())
                    .add(ModItems.LEAD_BOOTS.getId())
                    .add(ModItems.QUARTZ_BOOTS.getId())
                    .add(ModItems.REDSTONE_BOOTS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());

            getTagBuilder(ItemTags.ARMOR_ENCHANTABLE)
                    .add(ModItems.BRONZE_HELMET.getId())
                    .add(ModItems.BRONZE_CHESTPLATE.getId())
                    .add(ModItems.BRONZE_LEGGINGS.getId())
                    .add(ModItems.BRONZE_BOOTS.getId())
                    .add(ModItems.IRONCOPPER_HELMET.getId())
                    .add(ModItems.IRONCOPPER_CHESTPLATE.getId())
                    .add(ModItems.IRONCOPPER_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId())
                    .add(ModItems.AMETHYST_HELMET.getId())
                    .add(ModItems.AMETHYST_CHESTPLATE.getId())
                    .add(ModItems.AMETHYST_LEGGINGS.getId())
                    .add(ModItems.AMETHYST_BOOTS.getId())
                    .add(ModItems.EMERALD_HELMET.getId())
                    .add(ModItems.EMERALD_CHESTPLATE.getId())
                    .add(ModItems.EMERALD_LEGGINGS.getId())
                    .add(ModItems.EMERALD_BOOTS.getId())
                    .add(ModItems.LEAD_HELMET.getId())
                    .add(ModItems.LEAD_CHESTPLATE.getId())
                    .add(ModItems.LEAD_LEGGINGS.getId())
                    .add(ModItems.LEAD_BOOTS.getId())
                    .add(ModItems.QUARTZ_HELMET.getId())
                    .add(ModItems.QUARTZ_CHESTPLATE.getId())
                    .add(ModItems.QUARTZ_LEGGINGS.getId())
                    .add(ModItems.QUARTZ_BOOTS.getId())
                    .add(ModItems.REDSTONE_HELMET.getId())
                    .add(ModItems.REDSTONE_CHESTPLATE.getId())
                    .add(ModItems.REDSTONE_LEGGINGS.getId())
                    .add(ModItems.REDSTONE_BOOTS.getId())
                    .add(ModItems.LAVA_HELMET.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());

            getTagBuilder(ItemTags.EQUIPPABLE_ENCHANTABLE)
                    .add(ModItems.BRONZE_HELMET.getId())
                    .add(ModItems.BRONZE_CHESTPLATE.getId())
                    .add(ModItems.BRONZE_LEGGINGS.getId())
                    .add(ModItems.BRONZE_BOOTS.getId())
                    .add(ModItems.IRONCOPPER_HELMET.getId())
                    .add(ModItems.IRONCOPPER_CHESTPLATE.getId())
                    .add(ModItems.IRONCOPPER_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId())
                    .add(ModItems.AMETHYST_HELMET.getId())
                    .add(ModItems.AMETHYST_CHESTPLATE.getId())
                    .add(ModItems.AMETHYST_LEGGINGS.getId())
                    .add(ModItems.AMETHYST_BOOTS.getId())
                    .add(ModItems.EMERALD_HELMET.getId())
                    .add(ModItems.EMERALD_CHESTPLATE.getId())
                    .add(ModItems.EMERALD_LEGGINGS.getId())
                    .add(ModItems.EMERALD_BOOTS.getId())
                    .add(ModItems.LEAD_HELMET.getId())
                    .add(ModItems.LEAD_CHESTPLATE.getId())
                    .add(ModItems.LEAD_LEGGINGS.getId())
                    .add(ModItems.LEAD_BOOTS.getId())
                    .add(ModItems.QUARTZ_HELMET.getId())
                    .add(ModItems.QUARTZ_CHESTPLATE.getId())
                    .add(ModItems.QUARTZ_LEGGINGS.getId())
                    .add(ModItems.QUARTZ_BOOTS.getId())
                    .add(ModItems.REDSTONE_HELMET.getId())
                    .add(ModItems.REDSTONE_CHESTPLATE.getId())
                    .add(ModItems.REDSTONE_LEGGINGS.getId())
                    .add(ModItems.REDSTONE_BOOTS.getId())
                    .add(ModItems.LAVA_HELMET.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());

            getTagBuilder(ItemTags.DURABILITY_ENCHANTABLE)
                    .add(ModItems.BRONZE_SWORD.getId())
                    .add(ModItems.BRONZE_SHOVEL.getId())
                    .add(ModItems.BRONZE_PICKAXE.getId())
                    .add(ModItems.BRONZE_AXE.getId())
                    .add(ModItems.BRONZE_HOE.getId())
                    .add(ModItems.BRONZE_HELMET.getId())
                    .add(ModItems.BRONZE_CHESTPLATE.getId())
                    .add(ModItems.BRONZE_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId())
                    .add(ModItems.IRONCOPPER_SWORD.getId())
                    .add(ModItems.IRONCOPPER_SHOVEL.getId())
                    .add(ModItems.IRONCOPPER_PICKAXE.getId())
                    .add(ModItems.IRONCOPPER_AXE.getId())
                    .add(ModItems.IRONCOPPER_HOE.getId())
                    .add(ModItems.IRONCOPPER_HELMET.getId())
                    .add(ModItems.IRONCOPPER_CHESTPLATE.getId())
                    .add(ModItems.IRONCOPPER_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId())
                    .add(ModItems.AMETHYST_SWORD.getId())
                    .add(ModItems.AMETHYST_SHOVEL.getId())
                    .add(ModItems.AMETHYST_PICKAXE.getId())
                    .add(ModItems.AMETHYST_AXE.getId())
                    .add(ModItems.AMETHYST_HOE.getId())
                    .add(ModItems.AMETHYST_HELMET.getId())
                    .add(ModItems.AMETHYST_CHESTPLATE.getId())
                    .add(ModItems.AMETHYST_LEGGINGS.getId())
                    .add(ModItems.AMETHYST_BOOTS.getId())
                    .add(ModItems.EMERALD_SWORD.getId())
                    .add(ModItems.EMERALD_SHOVEL.getId())
                    .add(ModItems.EMERALD_PICKAXE.getId())
                    .add(ModItems.EMERALD_AXE.getId())
                    .add(ModItems.EMERALD_HOE.getId())
                    .add(ModItems.EMERALD_HELMET.getId())
                    .add(ModItems.EMERALD_CHESTPLATE.getId())
                    .add(ModItems.EMERALD_LEGGINGS.getId())
                    .add(ModItems.EMERALD_BOOTS.getId())
                    .add(ModItems.LEAD_SWORD.getId())
                    .add(ModItems.LEAD_SHOVEL.getId())
                    .add(ModItems.LEAD_PICKAXE.getId())
                    .add(ModItems.LEAD_AXE.getId())
                    .add(ModItems.LEAD_HOE.getId())
                    .add(ModItems.LEAD_HELMET.getId())
                    .add(ModItems.LEAD_CHESTPLATE.getId())
                    .add(ModItems.LEAD_LEGGINGS.getId())
                    .add(ModItems.LEAD_BOOTS.getId())
                    .add(ModItems.QUARTZ_SWORD.getId())
                    .add(ModItems.QUARTZ_SHOVEL.getId())
                    .add(ModItems.QUARTZ_PICKAXE.getId())
                    .add(ModItems.QUARTZ_AXE.getId())
                    .add(ModItems.QUARTZ_HOE.getId())
                    .add(ModItems.QUARTZ_HELMET.getId())
                    .add(ModItems.QUARTZ_CHESTPLATE.getId())
                    .add(ModItems.QUARTZ_LEGGINGS.getId())
                    .add(ModItems.QUARTZ_BOOTS.getId())
                    .add(ModItems.REDSTONE_HELMET.getId())
                    .add(ModItems.REDSTONE_CHESTPLATE.getId())
                    .add(ModItems.REDSTONE_LEGGINGS.getId())
                    .add(ModItems.REDSTONE_BOOTS.getId())
                    .add(ModItems.LAVA_HELMET.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId())
                    .add(ModItems.LAVA_BOOTS.getId())
                    .add(ModItems.DURABLE_FIREWORK_ROCKET.getId())
                    .add(ModItems.DURABLE_FIREWORK_ROCKET_UPGRADED.getId())
                    .add(ModItems.DURABLE_TOTEM_OF_UNDYING.getId())
                    .add(ModItems.DURABLE_TOTEM_OF_UNDYING_UPGRADED.getId())
                    .add(ModItems.DURABLE_TORCH.getId())
                    .add(ModItems.DURABLE_TORCH_UPGRADED.getId());

            getTagBuilder(ItemTags.HEAD_ARMOR_ENCHANTABLE)
                    .add(ModItems.BRONZE_HELMET.getId())
                    .add(ModItems.IRONCOPPER_HELMET.getId())
                    .add(ModItems.AMETHYST_HELMET.getId())
                    .add(ModItems.EMERALD_HELMET.getId())
                    .add(ModItems.LEAD_HELMET.getId())
                    .add(ModItems.QUARTZ_HELMET.getId())
                    .add(ModItems.REDSTONE_HELMET.getId())
                    .add(ModItems.LAVA_HELMET.getId());

            getTagBuilder(ItemTags.CHEST_ARMOR_ENCHANTABLE)
                    .add(ModItems.BRONZE_CHESTPLATE.getId())
                    .add(ModItems.IRONCOPPER_CHESTPLATE.getId())
                    .add(ModItems.AMETHYST_CHESTPLATE.getId())
                    .add(ModItems.EMERALD_CHESTPLATE.getId())
                    .add(ModItems.LEAD_CHESTPLATE.getId())
                    .add(ModItems.QUARTZ_CHESTPLATE.getId())
                    .add(ModItems.REDSTONE_CHESTPLATE.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId());

            getTagBuilder(ItemTags.LEG_ARMOR_ENCHANTABLE)
                    .add(ModItems.BRONZE_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_LEGGINGS.getId())
                    .add(ModItems.AMETHYST_LEGGINGS.getId())
                    .add(ModItems.EMERALD_LEGGINGS.getId())
                    .add(ModItems.LEAD_LEGGINGS.getId())
                    .add(ModItems.QUARTZ_LEGGINGS.getId())
                    .add(ModItems.REDSTONE_LEGGINGS.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId());

            getTagBuilder(ItemTags.FOOT_ARMOR_ENCHANTABLE)
                    .add(ModItems.BRONZE_BOOTS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId())
                    .add(ModItems.AMETHYST_BOOTS.getId())
                    .add(ModItems.EMERALD_BOOTS.getId())
                    .add(ModItems.LEAD_BOOTS.getId())
                    .add(ModItems.QUARTZ_BOOTS.getId())
                    .add(ModItems.REDSTONE_BOOTS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());

            getTagBuilder(ItemTags.TRIMMABLE_ARMOR)
                    .add(ModItems.BRONZE_HELMET.getId())
                    .add(ModItems.BRONZE_CHESTPLATE.getId())
                    .add(ModItems.BRONZE_LEGGINGS.getId())
                    .add(ModItems.BRONZE_BOOTS.getId())
                    .add(ModItems.IRONCOPPER_HELMET.getId())
                    .add(ModItems.IRONCOPPER_CHESTPLATE.getId())
                    .add(ModItems.IRONCOPPER_LEGGINGS.getId())
                    .add(ModItems.IRONCOPPER_BOOTS.getId())
                    .add(ModItems.AMETHYST_HELMET.getId())
                    .add(ModItems.AMETHYST_CHESTPLATE.getId())
                    .add(ModItems.AMETHYST_LEGGINGS.getId())
                    .add(ModItems.AMETHYST_BOOTS.getId())
                    .add(ModItems.EMERALD_HELMET.getId())
                    .add(ModItems.EMERALD_CHESTPLATE.getId())
                    .add(ModItems.EMERALD_LEGGINGS.getId())
                    .add(ModItems.EMERALD_BOOTS.getId())
                    .add(ModItems.LEAD_HELMET.getId())
                    .add(ModItems.LEAD_CHESTPLATE.getId())
                    .add(ModItems.LEAD_LEGGINGS.getId())
                    .add(ModItems.LEAD_BOOTS.getId())
                    .add(ModItems.QUARTZ_HELMET.getId())
                    .add(ModItems.QUARTZ_CHESTPLATE.getId())
                    .add(ModItems.QUARTZ_LEGGINGS.getId())
                    .add(ModItems.QUARTZ_BOOTS.getId())
                    .add(ModItems.REDSTONE_HELMET.getId())
                    .add(ModItems.REDSTONE_CHESTPLATE.getId())
                    .add(ModItems.REDSTONE_LEGGINGS.getId())
                    .add(ModItems.REDSTONE_BOOTS.getId())
                    .add(ModItems.LAVA_HELMET.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());

            getTagBuilder(ModTags.PIGLINS_LOVED_ARMOR)
                    .add(ModItems.LAVA_HELMET.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());

            getTagBuilder(ItemTags.PIGLIN_SAFE_ARMOR)
                    .addTag(ModTags.PIGLINS_LOVED_ARMOR.id());

            getTagBuilder(ItemTags.PIGLIN_LOVED)
                    .add(ModItems.LAVA_HELMET.getId())
                    .add(ModItems.LAVA_CHESTPLATE.getId())
                    .add(ModItems.LAVA_LEGGINGS.getId())
                    .add(ModItems.LAVA_BOOTS.getId());
        }
    }
}
