modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sptools"
version = "${version}"
displayName = "SupplementalTools"
authors = "shiri47s"
description = '''
Supplemental Tools provides subtle,
non-intrusive additions to enhance your everyday Minecraft gameplay experience.
'''
logoFile = "icon.png"

[[dependencies.sptools]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sptools]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sptools]]
modId = "architectury"
type = "required"
versionRange = "[16.1.4,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sptools.mixins.json"
