modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sptools"
version = "${version}"
displayName = "SupplementalTools"
authors = "shiri47s"
description = '''
Supplemental Tools provides subtle,
non-intrusive additions to enhance your everyday Minecraft gameplay experience.
'''
logoFile = "icon.png"

[[dependencies.sptools]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sptools]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sptools]]
modId = "architectury"
type = "required"
versionRange = "[21.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sptools]]
modId = "trinkets_updated"
type = "optional"
versionRange = "[4.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sptools.mixins.json"
