modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sptools"
version = "${version}"
displayName = "SupplementalTools"
authors = "shiri47s"
description = '''
This is a mod to add a set of equipment. The items to be added are crafted from copper, amethyst, emeralds, etc.
'''
#logoFile = ""

[[dependencies.sptools]]
modId = "neoforge"
type = "required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sptools]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sptools]]
modId = "architectury"
type = "required"
versionRange = "[12.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sptools.mixins.json"
